### PR TITLE
Various small improvements + different styles

### PR DESCRIPTION
**Pull request by voec**

### CODE REVIEW

**Comment by romligCH** [comment]
Nice changes.
I'd prefer to name the styles themes in the configuration. Additionnally we could disable animation for empty keys.

I'll also rewrite the monitor code to work with mixed dpi settings. I've already spent hours with those issues so I can fix it.

Finally, I'll fix the readme to indicate the new hotkey.

**Comment by voec** [comment]
Oh, I didn't know that commits I make after a pull request also get added into the original pull request.
So things like the capslock hotkey were just something I personally liked more, I hope my changes weren't too invasive.

But yeah, sounds great!

Tbh I've been locking for a nice tool like this for quite a while, so I'm glad I could contribute.

**Comment by romligCH** [comment]
I will add an option to enable the animation.
For the caps key, it avoids this ugly workaround of sending an alt key press after closing, so it's for the better.

I saw you removed the flags groups in your screenshot. Is it because they didn't show well or more because of the missing support in Windows?

**Comment by voec** [comment]
> I saw you removed the flags groups in your screenshot. Is it because they didn't show well or more because of the missing support in Windows?

Ah! No, that was an error I didn't notice when taking the screenshot!
I like the fallback idea though.

**Pull request merged**
